 CREATE TABLE ImportCont (
        VslCode              char(7) NOT NULL,
        VoyCtrl              int NOT NULL,
        ContNo               char(12) NOT NULL,
        BLNo                 char(20) NOT NULL,
        timestamp            timestamp NULL,
        UpdtTime             datetime NULL,
        UpdtPgCd             char(8) NOT NULL,
        UpdtTmnl             char(15) NOT NULL,
        RFFlag               char(1) NOT NULL,
        DGFlag               char(1) NOT NULL,
        HotFlag              char(1) NOT NULL,
        EstDelDate           datetime NULL,
        FreeTime             datetime NULL,
        OLTICFlag            char(1) NOT NULL,
        OLTICDate            datetime NULL,
        OLTICNo              char(15) NOT NULL,
        DOStatus             char(1) NOT NULL,
        DelPermitDate        datetime NULL,
        OLTDateFrom          datetime NULL,
        OLTDateTo            datetime NULL,
        ReturnPlace          char(20) NOT NULL,
        InTime               datetime NULL,
        CYDelTime            datetime NULL,
        SYDelTime            datetime NULL,
        WHArDate             datetime NULL,
        DevanTime            datetime NULL,
        ReturnTime           datetime NULL,
        CustStatus           char(1) NOT NULL,
        PRIMARY KEY (VslCode, VoyCtrl, ContNo, BLNo)
 )
go
 
 CREATE TABLE mVessel (
        VslCode              char(7) NOT NULL,
        timestamp            timestamp NULL,
        UpdtTime             datetime NULL,
        UpdtPgCd             char(8) NOT NULL,
        UpdtTmnl             char(15) NOT NULL,
        FullName             char(20) NOT NULL,
        ShipLine             char(5) NOT NULL,
        PRIMARY KEY (VslCode)
 )
go

 CREATE TABLE sTransaction1 (
        ComTime              datetime NOT NULL,
        SeqNo                int NOT NULL,
        TransCode            char(4) NOT NULL,
        timestamp            timestamp NULL,
        UpdtTime             datetime NOT NULL,
        UpdtPgCd             char(8) NOT NULL,
        UpdtTmnl             char(15) NOT NULL,
        Status               char(1) NOT NULL,
        Process              char(1) NOT NULL,
        Sender               char(20) NOT NULL,
        TransPlace           char(20) NOT NULL,
        Item001               char(20) NULL,
        Item002               char(20) NULL,
        Item003               char(20) NULL,
        Item004               char(20) NULL,
        Item005               char(20) NULL,
        Item006               char(20) NULL,
        Item007               char(20) NULL,
        Item008               char(20) NULL,
        Item009               char(20) NULL,
        Item010               char(20) NULL,
        Item011               char(20) NULL,
        Item012               char(20) NULL,
        Item013               char(20) NULL,
        Item014               char(20) NULL,
        Item015               char(20) NULL,
        Item016               char(20) NULL,
        Item017               char(20) NULL,
        Item018               char(20) NULL,
        Item019               char(20) NULL,
        Item020               char(20) NULL,
        Item021               char(20) NULL,
        Item022               char(20) NULL,
        Item023               char(20) NULL,
        Item024               char(20) NULL,
        Item025               char(20) NULL,
        Item026               char(20) NULL,
        Item027               char(20) NULL,
        Item028               char(20) NULL,
        Item029               char(20) NULL,
        Item030               char(20) NULL,
        Item031               char(20) NULL,
        Item032               char(20) NULL,
        Item033               char(20) NULL,
        Item034               char(20) NULL,
        Item035               char(20) NULL,
        Item036               char(20) NULL,
        Item037               char(20) NULL,
        Item038               char(20) NULL,
        Item039               char(20) NULL,
        Item040               char(20) NULL,
        Item041               char(20) NULL,
        Item042               char(20) NULL,
        Item043               char(20) NULL,
        Item044               char(20) NULL,
        Item045               char(20) NULL,
        Item046               char(20) NULL,
        Item047               char(20) NULL,
        Item048               char(20) NULL,
        Item049               char(20) NULL,
        Item050               char(20) NULL,
        Item051               char(20) NULL,
        Item052               char(20) NULL,
        Item053               char(20) NULL,
        Item054               char(20) NULL,
        Item055               char(20) NULL,
        Item056               char(20) NULL,
        Item057               char(20) NULL,
        Item058               char(20) NULL,
        Item059               char(20) NULL,
        Item060               char(20) NULL,
        Item061               char(20) NULL,
        Item062               char(20) NULL,
        Item063               char(20) NULL,
        Item064               char(20) NULL,
        Item065               char(20) NULL,
        Item066               char(20) NULL,
        Item067               char(20) NULL,
        Item068               char(20) NULL,
        Item069               char(20) NULL,
        Item070               char(20) NULL,
        Item071               char(20) NULL,
        Item072               char(20) NULL,
        Item073               char(20) NULL,
        Item074               char(20) NULL,
        Item075               char(20) NULL,
        Item076               char(20) NULL,
        Item077               char(20) NULL,
        Item078               char(20) NULL,
        Item079               char(20) NULL,
        Item080               char(20) NULL,
        Item081               char(20) NULL,
        Item082               char(20) NULL,
        Item083               char(20) NULL,
        Item084               char(20) NULL,
        Item085               char(20) NULL,
        Item086               char(20) NULL,
        Item087               char(20) NULL,
        Item088               char(20) NULL,
        Item089               char(20) NULL,
        Item090               char(20) NULL,
        Item091               char(20) NULL,
        Item092               char(20) NULL,
        Item093               char(20) NULL,
        Item094               char(20) NULL,
        Item095               char(20) NULL,
        Item096               char(20) NULL,
        Item097               char(20) NULL,
        Item098               char(20) NULL,
        Item099               char(20) NULL,
        Item100               char(20) NULL,
        Item101               char(20) NULL,
        Item102               char(20) NULL,
        Item103               char(20) NULL,
        Item104               char(20) NULL,
        Item105               char(20) NULL,
        Item106               char(20) NULL,
        Item107               char(20) NULL,
        Item108               char(20) NULL,
        Item109               char(20) NULL,
        Item110               char(20) NULL,
        Item111               char(20) NULL,
        Item112               char(20) NULL,
        Item113               char(20) NULL,
        Item114               char(20) NULL,
        Item115               char(20) NULL,
        Item116               char(20) NULL,
        Item117               char(20) NULL,
        Item118               char(20) NULL,
        Item119               char(20) NULL,
        Item120               char(20) NULL,
        Item121               char(20) NULL,
        Item122               char(20) NULL,
        Item123               char(20) NULL,
        Item124               char(20) NULL,
        Item125               char(20) NULL,
        Item126               char(20) NULL,
        Item127               char(20) NULL,
        Item128               char(20) NULL,
        Item129               char(20) NULL,
        Item130               char(20) NULL,
        Item131               char(20) NULL,
        Item132               char(20) NULL,
        Item133               char(20) NULL,
        Item134               char(20) NULL,
        Item135               char(20) NULL,
        Item136               char(20) NULL,
        Item137               char(20) NULL,
        Item138               char(20) NULL,
        Item139               char(20) NULL,
        Item140               char(20) NULL,
        Item141               char(20) NULL,
        Item142               char(20) NULL,
        Item143               char(20) NULL,
        Item144               char(20) NULL,
        Item145               char(20) NULL,
        Item146               char(20) NULL,
        Item147               char(20) NULL,
        Item148               char(20) NULL,
        Item149               char(20) NULL,
        Item150               char(20) NULL,
        PRIMARY KEY (ComTime, SeqNo, TransCode)
 )
go
