 CREATE TABLE sTransaction (
        ComTime              datetime NOT NULL,
        SeqNo                int NOT NULL,
        TransCode            char(4) NOT NULL,
        timestamp            timestamp NULL,
        UpdtTime             datetime NULL,
        UpdtPgCd             char(8) NOT NULL,
        UpdtTmnl             char(15) NOT NULL,
        Status               char(1) NOT NULL,
        Process              char(1) NOT NULL,
        Sender               char(20) NOT NULL,
        TransPlace           char(20) NOT NULL,
        Item01               char(20) NULL,
        Item02               char(20) NULL,
        Item03               char(20) NULL,
        Item04               char(20) NULL,
        Item05               char(20) NULL,
        Item06               char(20) NULL,
        Item07               char(20) NULL,
        Item08               char(20) NULL,
        Item09               char(20) NULL,
        Item10               char(20) NULL,
        Item11               char(20) NULL,
        Item12               char(20) NULL,
        Item13               char(20) NULL,
        Item14               char(20) NULL,
        Item15               char(20) NULL,
        Item16               char(20) NULL,
        Item17               char(20) NULL,
        Item18               char(20) NULL,
        Item19               char(20) NULL,
        Item20               char(20) NULL,
        PRIMARY KEY (ComTime, SeqNo, TransCode)
 )
go
