vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|22 Jul 2003 07:10:26 -0000
vti_extenderversion:SR|4.0.2.7802
vti_cacheddtm:TX|22 Jul 2003 07:10:26 -0000
vti_filesize:IR|3856
vti_cachedlinkinfo:VX|S|gif/back.gif S|gif/requestt.gif S|gif/logo2.gif A|request-syori.asp S|gif/botan.gif S|gif/hr.gif H|mailto:morisaki.t01@city.fukuoka.jp
vti_cachedsvcrellinks:VX|FSUS|gif/back.gif FSUS|gif/requestt.gif FSUS|gif/logo2.gif FAUS|request-syori.asp FSUS|gif/botan.gif FSUS|gif/hr.gif NHUS|mailto:morisaki.t01@city.fukuoka.jp
vti_cachedbodystyle:SR|<body bgcolor="DEE1FF" text="#000000" link="#3300FF" background="gif/back.gif" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=Shift_JIS
vti_backlinkinfo:VX|
